---
title: "reading_data"
author: "Yiqun Jin"
date: "10/21/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(rvest)

library(p8105.datasets)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## String vectors

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff") #strings are case sensitive
#str_replace(string_vec, "e", "This is an uppercase E")
str_replace(string_vec, "jeff", "")
```

regular expressions

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") #`^` represent the beginning of the line
str_detect(string_vec, "i think$") # `$` represent the end of the line
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )
str_detect(string_vec,"bush")
str_detect(string_vec,"[Bb]ush") #upper case or lower case, both fine
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]") #find everything that start with number and then a letter
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # `.` represent everything
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") #the actual `[`
```

## Vector

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
```

